### ISSUE TITLE
Doesn't Even Work

### ISSUE THREAD

**Issue by ghost** [capnramses/obj2json#1]
Program segfaults. 0/10.

**Comment by capnramses** [comment]
i'm guessing it's one of:
* mesh must have vertex positions, normals, and texture coordinates
* mesh must be triangulated
no?

**Comment by capnramses** [comment]
sample .obj:

g Cube
v 1.000000 -1.000000 -1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 -1.000000 1.000000
v -1.000000 -1.000000 -1.000000
v 1.000000 1.000000 -0.999999
v 0.999999 1.000000 1.000001
v -1.000000 1.000000 1.000000
v -1.000000 1.000000 -1.000000
vt 1.000000 0.000000
vt 1.000000 1.000000
vt 0.000000 1.000000
vt 1.000000 0.999999
vt 0.000000 0.000000
vt 0.999999 1.000000
vt 0.999999 0.000000
vn 0.000000 -1.000000 0.000000
vn -0.000000 1.000000 0.000000
vn 1.000000 -0.000000 0.000001
vn -0.000000 -0.000000 1.000000
vn -1.000000 -0.000000 -0.000000
vn 0.000000 0.000000 -1.000000
vn 1.000000 0.000000 -0.000000
s off
f 1/1/1 2/2/1 3/3/1
f 5/4/2 8/3/2 7/5/2
f 1/1/3 5/6/3 6/3/3
f 2/1/4 6/6/4 3/5/4
f 3/1/5 7/6/5 4/5/5
f 5/3/6 1/5/6 4/7/6
f 4/5/1 1/1/1 3/3/1
f 6/7/2 5/4/2 7/5/2
f 2/5/7 1/1/7 6/3/7
f 6/6/4 7/3/4 3/5/4
f 7/6/5 8/3/5 4/5/5
f 8/2/6 5/3/6 4/7/6
